---
- name: prepare for internal network env setup
  hosts: all
  tasks:
  - name: download helm tgz to local
    get_url:
      url: "{{ helm_url }}"
      dest: files/{{ helm_url | basename }}
    when: inventory_hostname == "localhost"
